### ISSUE TITLE
Implement round, ceil, floor et.c functions?

### ISSUE THREAD

**Issue by legolord208** [akubera/bigdecimal-rs#24]
EDIT: I recently changed the title to something completely irrelevant.
Original title: `No bitwise operators?`

Traits like `Shl` seems to be missing :open_mouth:

**Comment by kestred** [comment]
This may be me lacking sufficient mathematical backing, but I'm not sure what the expected behavior for say, `Shl` would be?

Do you mean `impl Shl<usize> for BigDecimal` and other integers (or vice versa)?
What should you expect the result of `BigDecimal::from(10.99) << 10` to be?

It would seem to me that a BigDecimal doesn't have a well defined bitwise representation, unlike say `BigInteger`.   In this case BigDecimal is much more like `Rational`, `BigRational`, or `Complex` as an alternative representation to floating-point numbers which don't support Bitwise operators.


     NOTE: As I am only an interested contributor to BigDecimal and not the crate author
     nor a mathematician, please take these thoughts with a grain of salt.

**Comment by legolord208** [comment]
That's a good point. `f32` doesn't even implement `Shl`.  
Perhaps this is a really bad idea.

What should be implemented though, is `round` and similar. Sure, `to_bigint` exists, but it's not exactly rounding...

**Comment by kestred** [comment]
(See also https://github.com/akubera/bigdecimal-rs/issues/14 and https://github.com/akubera/bigdecimal-rs/issues/21).
