### ISSUE TITLE
`with_prec` sometimes adds erroneous 1 to the `BigInt` part of the result

### ISSUE THREAD

**Issue by colt-browning** [akubera/bigdecimal-rs#47]
```rust
let x = BigDecimal::parse_bytes(b"1.0001", 10).unwrap();
assert_eq!(x.with_prec(5), x);
assert_eq!(x.with_prec(4), BigDecimal::one());
let x = BigDecimal::parse_bytes(b"1.00009", 10).unwrap();
assert_eq!(x.with_prec(6), x);
assert_eq!(x.with_prec(5), BigDecimal::parse_bytes(b"1.0001", 10).unwrap());
assert_eq!(x.with_prec(4), BigDecimal::one());
assert_ne!(x.with_prec(4), BigDecimal::parse_bytes(b"1.001", 10).unwrap());
```
First four assertions (properly) succeed, but last two assertions fail, which seems to be a bug.

Perhaps could be fixed together with implementing #14.

**Comment by akubera** [comment]
mmhmmm... It was doing `div_mod(100009, 100) -> 1000, 9` and getting the rounding term from '9' instead of what should have been '0' in '09'. Seems subtle but I'm surprised this didn't show up somewhere else where I use `with_prec`.

This is fixed by multiplying the remainder by 10 and seeing if the value is less than the quotient (in this case 9 * 10 = 90 < 100); this indicates the left-most digit is zero. If not, then perform the rounding as before.

Thanks a lot for finding this!

Fixed in c5a7622c29ef0fe2bda7
